services:
  ch-pg-1:
    image: postgres:18.3-trixie
    container_name: ch-pg-1
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - ch-net
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - -c
      - listen_addresses=*
    volumes:
      - ch-pg-1-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${PG_USER} -d ${PG_DATABASE} -h 127.0.0.1 -p 5432' ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ch-pg-1-data:
    name: ch-pg-1-data
    external: false