services:
  ch-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ch-webui
    restart: unless-stopped
    networks:
      - ch-net
      - dwh-net
    volumes:
      - ch-webui-data:/app/backend/data
    ports:
      - '29080:8080'
    environment:
      - 'OLLAMA_BASE_URL=http://loki:31434'
      - 'WEBUI_SECRET_KEY='

volumes:
  ch-webui-data:
    name: ch-webui-data
    external: false
